--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: case_insensitive; Type: COLLATION; Schema: public; Owner: postgres
--

CREATE COLLATION public.case_insensitive (provider = icu, deterministic = false, locale = 'und-u-ks-level2');


ALTER COLLATION public.case_insensitive OWNER TO postgres;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
    NEW.updated_at = now();
    return NEW;
end;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

--
-- Name: trigger_updated_at(regclass); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.trigger_updated_at(tablename regclass) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
    execute format('CREATE TRIGGER set_updated_at
        BEFORE UPDATE
        ON %s
        FOR EACH ROW
        WHEN (OLD is distinct from NEW)
    EXECUTE FUNCTION set_updated_at();', tablename);
end;
$$;


ALTER FUNCTION public.trigger_updated_at(tablename regclass) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brand (
    brand_id uuid DEFAULT public.uuid_generate_v1mc() NOT NULL,
    name text NOT NULL COLLATE public.case_insensitive,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);


ALTER TABLE public.brand OWNER TO postgres;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO postgres;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    product_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL COLLATE public.case_insensitive,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    brand_id uuid NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Data for Name: brand; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.brand (brand_id, name, created_at, updated_at, deleted_at) FROM stdin;
600db29c-6582-11f0-b2b5-fb7d49abd058	Haruharu WONDER	2025-07-20 15:58:28.008402+00	\N	\N
508f8c0e-6583-11f0-b2b5-23fbeb044c99	Torriden	2025-07-20 16:05:11.518966+00	\N	\N
94e344ae-6583-11f0-b2b5-3fd8eca12b0f	Torriden_delete	2025-07-20 16:07:06.152695+00	\N	\N
\.


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2025-07-18 15:40:29.563847
2	20250718145812	t	2025-07-18 15:40:29.585937
3	20250718145853	t	2025-07-18 15:40:29.611298
4	20250718150017	t	2025-07-18 15:40:29.618359
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (product_id, name, description, price, stock, created_at, updated_at, deleted_at, brand_id) FROM stdin;
5bb4e216-08f7-4a1c-bcc0-bdbd9a937b38	Torriden DIVE IN Low Molecular Hyaluronic Acid Serum 50ml	Torriden DIVE IN Low Molecular Hyaluronic Acid Serum 50ml	220000.00	800	2025-07-20 16:10:12.397005+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
57659db8-6198-4cb3-b722-16dc600c2cd6	Torriden DIVE IN Low Molecular Hyaluronic Acid Soothing Cream 100ml	Torriden DIVE IN Low Molecular Hyaluronic Acid Soothing Cream 100ml	420000.00	500	2025-07-20 16:10:53.887033+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
894ddb74-5a40-4e50-8b4b-42d4dccf837a	Torriden Balanceful Cica Toner Pad 60pcs	Torriden Balanceful Cica Toner Pad 60pcs	230000.00	500	2025-07-20 16:11:58.766838+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
a81eedce-bdff-4d98-9a93-fc24cb967303	Torriden DIVE IN Low Molecular Hyaluronic Acid Cleansing Foam 150ml	Torriden DIVE IN Low Molecular Hyaluronic Acid Cleansing Foam 150ml	250000.00	500	2025-07-20 16:12:27.147216+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
1753d0bd-97bb-4523-abc6-b3b5f4e5b0bf	Torriden Balanceful Cica Serum 50ml	Torriden Balanceful Cica Serum 50ml	230000.00	500	2025-07-20 16:13:03.554001+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
dbab1cc8-4d9a-41cc-9a3d-4bc2eda41dab	Torriden Balanceful Cica Cream 80ml	Torriden Balanceful Cica Cream 80ml	240000.00	500	2025-07-20 16:13:28.47329+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
2ad160d8-3113-4bdc-8597-2e5893bc699d	Torriden Balanceful Cica Cleansing Gel 200ml	Torriden Balanceful Cica Cleansing Gel 200ml	200000.00	500	2025-07-20 16:14:36.174921+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
7b7b0376-c39d-4d84-bed6-d0f7f61578d7	Torriden Solid In Ceramide Lip Essence 11ml	Torriden Solid In Ceramide Lip Essence 11ml	120000.00	500	2025-07-20 16:14:58.008172+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
51fdd7f6-7a42-4254-a26d-bd7f1377bdf1	Torriden DIVE IN Low Molecular Hyaluronic Acid Mask Sheet 10ea	Torriden DIVE IN Low Molecular Hyaluronic Acid Mask Sheet 10ea	400000.00	500	2025-07-20 16:15:21.610058+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
644c0f90-bf60-45ff-8c0e-7bae3c3ba72d	Torriden Solid In Ceramide All Day Essence 100ml	Torriden Solid In Ceramide All Day Essence 100ml	360000.00	500	2025-07-20 16:16:17.667526+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
af6507e2-e85d-4ee9-bb57-7d997bbf15ab	Torriden DIVE IN Low Molecular Hyaluronic Acid Cream 80ml	Torriden DIVE IN Low Molecular Hyaluronic Acid Cream 80ml	300000.00	500	2025-07-20 16:16:44.415373+00	\N	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
ad148a4d-c424-4e89-9173-95829adca7ee	Torriden DIVE IN Low Molecular Hyaluronic Acid Toner 300ml Updated	Torriden DIVE IN Low Molecular Hyaluronic Acid Toner 300ml Updated	320000.00	500	2025-07-20 16:11:25.040585+00	2025-07-20 16:23:17.622458+00	\N	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
a3ea7e5c-2d6d-4bc7-9834-cc58662f8561	Torriden DIVE IN Low Molecular Hyaluronic Acid Skin Booster 200ml	Torriden DIVE IN Low Molecular Hyaluronic Acid Skin Booster 200ml	300000.00	500	2025-07-20 16:15:48.926767+00	2025-07-20 16:24:51.89049+00	2025-07-20 16:24:51.89049+00	94e344ae-6583-11f0-b2b5-3fd8eca12b0f
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 4, true);


--
-- Name: brand brand_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_name_key UNIQUE (name);


--
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (brand_id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: product product_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_name_key UNIQUE (name);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (product_id);


--
-- Name: brand set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.brand FOR EACH ROW WHEN ((old.* IS DISTINCT FROM new.*)) EXECUTE FUNCTION public.set_updated_at();


--
-- Name: product set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.product FOR EACH ROW WHEN ((old.* IS DISTINCT FROM new.*)) EXECUTE FUNCTION public.set_updated_at();


--
-- Name: product product_brand_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brand(brand_id);


--
-- PostgreSQL database dump complete
--

